import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Inter } from "next/font/google";
import { Providers } from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-w-screen flex min-h-screen items-center justify-center">
        <Providers>
          <main
            className={`bgc2 relative m-auto max-h-90 min-h-400 min-w-70 max-w-90 rounded-md p-10 text-center shadow-2xl shadow-black ${inter.className}`}>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
