import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Inter } from "next/font/google";
import { Providers } from "@/redux/Provider";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className)}>
        <Providers>
          <main className="flex h-full min-h-screen flex-col items-center justify-center gap-5 pt-5 pb-10 md:gap-10">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
